[base]
name = analysis_neuro
testdeps =
    mock
    pytest
    coverage

[tox]
envlist =
    check-version
    check-packaging
    coverage
    docs
    lint
    py38

minversion = 3.1.0

# ignore basepython for envs that already specify a version
ignore_basepython_conflict = true

[testenv]
basepython=python3
setenv =
    PIP_INDEX_URL = https://bbpteam.epfl.ch/repository/devpi/simple
deps = {[base]testdeps}
commands = pytest tests

[testenv:check-version]
skip_install = true
deps = bbp-nse-ci
commands = do_release.py -p . check-version


[testenv:coverage]
deps =
    {[base]testdeps}
    coverage
commands =
    coverage run --source {[base]name} -m pytest {[base]name}/tests
    coverage report --show-missing --fail-under=100
    coverage xml

[testenv:docs]
changedir = doc
extras = docs
deps = sphinx
commands = make html SPHINXOPTS=-W
whitelist_externals = make


[testenv:check-packaging]
deps =
    wheel
    twine
commands =
    python setup.py sdist bdist_wheel -d {envtmpdir}/dist
    twine check {envtmpdir}/dist/*

[testenv:lint]
deps =
    pycodestyle
    pydocstyle
    pylint
commands =
    pycodestyle {[base]name}
    pydocstyle {[base]name}
    pylint {[base]name}

# E731: do not assign a lambda expression, use a def
# W503: line break after binary operator
# W504: line break before binary operator
[pycodestyle]
ignore = E731,W503,W504,E721
max-line-length = 100

[pydocstyle]
# ignore the following
#   - D413: no blank line afer last section
add-ignore = D413
convention = google
