"""Terminology used in validation."""

REGION = "region"
LAYER = "layer"
NEURON_OR_GLIA = "neuron or glia?"
CELL_DENSITY = "cell density ($cells/mm^3$)"
CELL_COUNT = "cell count"
REGION_VOLUME = "volume ($mm^3$)"
DATASET = "dataset"
CITATION = "citation"
NOTES = "notes"
HEMISPHERE = "hemisphere"
SQERROR = "squared error"
